https://colab.research.google.com/drive/13_QAMaBXXXCGvPg5GgHvKAdK1GNVfY5h?usp=sharing

# NumPy: Numerical Python

NumPy (Numerical Python) is a Python library used for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.

## Why Learn NumPy?

NumPy is essential for anyone working in data analysis, machine learning, or scientific computing because:

- It allows efficient handling of large datasets.
- It forms the foundation for libraries like pandas, scikit-learn, TensorFlow, and PyTorch.
- It supports vectorized operations, enabling faster computations compared to Python loops.

In [7]:
# Importing NumPy
import numpy as np
# Creating a 1D array
arr = np.array([1,2,3,4,5])

print("NumPy array: ",arr)

NumPy array:  [1 2 3 4 5]


### Creating Arrays

NumPy provides several methods to create arrays efficiently:

```python
# 2D array using nested lists
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)

# Array of zeros
zeros = np.zeros((2, 3))
print(zeros)

# Array of ones
ones = np.ones((3, 3))
print(ones)

# Array with a range of numbers
range_array = np.arange(0, 10, 2)  # 0 to 10, step 2
print(range_array)
```

In [29]:
# Example: Creating Arrays
# 2D array using nested lists
arr_2d = np.array([[1,2,3],[3,4,5]])
print(arr_2d)

# Array of zeros
zeros = np.zeros((2,3))
print(zeros)

# Array of ones
ones = np.ones((2,3))
print(ones)
ones[1][1]= 5
print(ones)

# Array with a range of numbers
range_array = np.arange(0,10,2)
range_array

[[1 2 3]
 [3 4 5]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 5. 1.]]


array([0, 2, 4, 6, 8])

In [32]:
# we can also define the data type while creating an array, as the default data type is float.
# the first value in shape of array is for rows and second for column.

zeros = np.zeros((2,3), dtype=int)
print(zeros)

ones = np.ones((2,3), dtype=int)
print(ones)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [40]:
range_array = np.arange(0,23,2)
range_array = range_array.reshape((3,4))

range_array

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a = np.arange()

In [25]:
arr_2d = np.array([
    [1,2,3],
    [3,4,5]
])
print(arr_2d)

[[1 2 3]
 [3 4 5]]


### Array Operations

NumPy allows arithmetic operations on arrays directly:

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print(a + b)

# Element-wise multiplication
print(a * b)

# Scalar operations
print(a * 2)
```

In [55]:
# Example: Array Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print(a + b)

# Element-wise multiplication
print(a * b)

# Scalar operations
print(a * 2)

[5 7 9]
[ 4 10 18]
[2 4 6]


In [56]:
a = np.array([[1, 2, 3],[1,2,3]])
#b = np.array([[4, 5, 6],[1,2,3]])

print(a)
print(b)
print(a + b)

[[1 2 3]
 [1 2 3]]
[4 5 6]
[[5 7 9]
 [5 7 9]]


In [58]:
# addition
ad = np.add(a,b)

ad

array([[5, 7, 9],
       [5, 7, 9]])

In [59]:
# multiplication
ml = np.multiply(a,b)
ml

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [62]:
# multiplication
c = np.array([[ 4, 10, 18],
       [ 4, 10, 18]])

print(c*3)

[[12 30 54]
 [12 30 54]]


In [63]:
# raise to power
p = np.power(a,2)
p

array([[1, 4, 9],
       [1, 4, 9]])

In [64]:
# raise to power
print(p**3)

[[  1  64 729]
 [  1  64 729]]


### Indexing, Slicing, and Reshaping

In [65]:
a = np.array([[1,2,3], [4,5,6]])

b = np.array([[7,8,9],[4,5,6]])

In [68]:
a = np.array(([1,2],(3,4)))

a

array([[1, 2],
       [3, 4]])

In [76]:
arr = np.array([1,2,3,4,5,6])
# Accessing Elements
print(arr[0])
print(arr[-1])

# Slicing
print(arr[1:5])


# Reshaping
arr.reshape(2,3)

1
6
[2 3 4 5]


array([[1, 2, 3],
       [4, 5, 6]])

### Practical Applications

In [90]:
# Mathematical Functions
print(a)
print()

[[1 2]
 [3 4]]

Sum:  10
Mean:  2.5
Min:  1
Max:  4
Std. dev:  1.118033988749895
Std. dev:  1.118033988749895
Std. var:  1.25


AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [91]:
#np.sum()
print('Sum: ',a.sum())
np.sum(a)

Sum:  10


10

In [92]:
# np.mean()
print('Mean: ',a.mean())
np.mean(a)

Mean:  2.5


2.5

In [93]:
# np.min()
print('Min: ',a.min())
np.min(a)

Min:  1


1

In [94]:
# np.max()
print('Max: ',a.max())
np.max(a)

Max:  4


4

In [95]:

# np.std()
print('Std. dev: ',a.std())
np.std(a)

Std. dev:  1.118033988749895


1.118033988749895

In [97]:
# np.median()
print('Std. dev: ',a.std())
np.std(a)

Std. dev:  1.118033988749895


1.118033988749895

In [98]:
# np.var()
print('Std. var: ',a.var())
np.var(a)

Std. var:  1.25


1.25

In [102]:
# np.unique()
#print('Unique: ',a.unique())
np.unique(a)

array([1, 2, 3, 4])

In [101]:
#Square Root
print('Square Root: ',np.sqrt(a))
np.sqrt(a)

Square Root:  [[1.         1.41421356]
 [1.73205081 2.        ]]


array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### Questions

In [109]:
data = np.array([25, 32, 45, 28, 35, 40, 38, 22, 30, 42, 42, 100])

In [112]:
# Question 1: Calculate the mean, median, and standard deviation of a dataset.
print("Mean: ",np.mean(data))

print("Median: ",np.median(data))

print("Standard Deviation: ",np.std(data))

Mean:  39.916666666666664
Median:  36.5
Standard Deviation:  19.405576231817722


In [113]:
np.sort(data)

array([ 22,  25,  28,  30,  32,  35,  38,  40,  42,  42,  45, 100])

In [117]:
# Question 2: Find the unique values and their frequencies in a dataset.
data = np.array([25, 32, 45, 28, 35, 40, 38, 22, 30, 42, 42, 100])
unique, count = np.unique(data, return_counts=True)

print(unique, count)

[ 22  25  28  30  32  35  38  40  42  45 100] [1 1 1 1 1 1 1 1 2 1 1]


In [125]:
# Question 3: Filter data based on a condition.
data = np.array([25, 32, 45, 28, 35, 40, 38, 22, 30, 42, 42, 100])

c = data>30

data[c]

array([ 32,  45,  35,  40,  38,  42,  42, 100])

In [126]:
data = np.array([25, 32, 45, 28, 35, 40, 38, 22, 30, 42, 42, 100])

data[data>30]

array([ 32,  45,  35,  40,  38,  42,  42, 100])

In [118]:
# Question 4: Reshape a 1D array into a 2D array.
data.reshape(3,4)

array([[ 25,  32,  45,  28],
       [ 35,  40,  38,  22],
       [ 30,  42,  42, 100]])

In [134]:
# Question 5: Replace missing values in a dataset with a specific value.
# Handling missing data is crucial for accurate analysis. This example replaces missing values (represented by NaN) with the mean of the dataset.

data = np.array([18,22,np.nan,28,23,np.nan,30])
np.mean(data)

nan

In [135]:
np.nanmean(data)

24.2

In [136]:
np.isnan(data)

array([False, False,  True, False, False,  True, False])

In [147]:
data = np.array([18,22,np.nan,28,23,np.nan,30])

mean = np.mean(data)

data[np.isnan(data)]=mean

data

array([18., 22., nan, 28., 23., nan, 30.])

In [148]:
data = np.array([18,22,np.nan,28,23,np.nan,30])

data[np.isnan(data)]=10

data

array([18., 22., 10., 28., 23., 10., 30.])

In [151]:
data = np.array([-5, 12, -9, 45, -23, 30])

data[data<0]=0

data

array([ 0, 12,  0, 45,  0, 30])

In [174]:
data = np.array([[5,10,15],
                [20, 25, 30],
                [35,40,45]])

#data[rows,col]
data[  : ,   0]>10

#f = data[row         ,0]
f = data[data[:,0]>10,0]

print(f)

[20 35]


In [167]:
data[:,0]

array([ 5, 20, 35])

In [176]:
# np.where(condition, value_if_true, value_if_false)

data = np.array([10,55,25,70,40,80])

r = np.where(data>50, 100, data)

print(r)

[ 10 100  25 100  40 100]


Create a 1D array with numbers from 10 to 50.

Create a 3x3 matrix with values ranging from 0 to 8.

Reverse an array of numbers from 1 to 10.

Find the mean and standard deviation of an array.

Replace all even numbers in an array with -1.

Find the unique elements and their frequencies in a dataset.

Extract all numbers greater than 25 from an array.

Reshape an array of size 16 into a 4x4 matrix.

Replace NaN values in an array with the column mean.

Find the cumulative sum of a given array.

Multiply two matrices using NumPy.

Normalize an array between 0 and 1.

Stack two arrays vertically and horizontally.

Compute the dot product of two vectors.

Create an identity matrix of size 5x5.

Replace values in an array based on a condition using np.where().

Create an array of 20 random numbers and find the top 5 highest values.

Perform element-wise division of two arrays and handle division by zero.

Extract the diagonal elements of a square matrix.

Convert a NumPy array to a Python list.

Find the determinant and inverse of a matrix.

Create a random matrix and sort its rows by the second column.

Implement a moving average on a 1D NumPy array.

Create a function that removes outliers from an array using standard deviation.

Perform one-hot encoding on a categorical array.

Generate a 10x10 matrix with random values and normalize its columns.

Compute the Pearson correlation coefficient between two arrays.

Perform matrix multiplication without using NumPy’s built-in function.

Create a NumPy-based simple linear regression model.

Implement a function to find the Euclidean distance between two points using NumPy.